spring:
  profiles: test

kroger:
  #to be used as a master switch
  cspVersionSwitch: v1
  oauth:
    default-target-uri: ${vcap.services.cspux-auth.credentials.defaultTargetUri}
    logout-uri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/logout
  krypt:
    aes:
      encryptedKey: ${vcap.services.cspux-encryptionkey.credentials.encryptedKey}
  imagedata:
    viewangles: front, back, top, bottom, left, right
    size:
      kwikee: 1000x1000
      gladson: 1000x1000
    background:
      kwikee: white
      gladson: transparent
    #placeholder for image type
    imagetype:
      kwikee: jpeg
      gladson: jpeg
  serverendpoints:
    add: /imp/ui/v2/server/addImage
    search: /imp/ui/v1/server/cspSearch
    vendorsearch: /imp/ui/v1/server/vendorSearch
    retrieval: https://impcoremgtdev.cfcdcinternaltest.kroger.com/imp/asset/v2/images/
  v1:
    add:
      url: https://imptest.cfcdcinternaltest.kroger.com/imp/asset/v1/images/add
    search:
      url: https://imp-search-test.cfcdcinternaltest.kroger.com/imp/search/v1/images/search
    authorization: U2NtYWRtaW46UTVwWUFmYVgyM1ZJMmhyZDJ1
  v2:
    add:
      url: https://impcore-asset-dev.cfcdcinternaltest.kroger.com/imp/asset/v2/images/add
    search:
      url: https://imp-search-test.cfcdcinternaltest.kroger.com/imp/search/v2/images/search
    authorization: U2NtYWRtaW46UTVwWUFmYVgyM1ZJMmhyZDJ1

security:
  oauth2:
    client:
      clientId: ${vcap.services.cspux-auth.credentials.clientId}
      clientSecret: ${vcap.services.cspux-auth.credentials.clientSecret}
      accessTokenUri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/oauth/token
      userAuthorizationUri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/oauth/authorize
    resource:
      tokenInfoUri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/oauth/check_token
