spring:
  application:
    name: Content Services Platform UI App
  output:
    ansi:
      enabled: detect
  profiles:
    active: local,SPOOFING
  mvc:
    view:
      suffix: .html
kroger:
  ldap:
    filter-order: -10
  management:
    security:
      roles: oa-cspux-support-5420
      enabled: false
  eaf:
    version: 5.0.2
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,krypt,keepalive,refresh
  endpoint:
    health:
      show-details: always
  health:
    ldap:
      enabled: false
---
spring:
  profiles: local

kroger:
#to be used as a master switch
  cspVersionSwitch: v2
  oauth:
    default-target-uri: http://localhost:8080
    logout-uri: https://federation.kroger.com/identity/logout
  krypt:
    aes:
      #encryptedKey: +eVf2H5Ban/uafJhPkJBBecUTXQuC15GK9va4MnsWLScEi4cYAC2/Fm4AsX3VhPZ
      encryptedKey: uY266kD0KlmVxQxa1gLAvSCFdAFtS4OBh/kT4oQsAEO1ujL/BlkhpqXohd8HDDW8
  imagedata:
    viewangles: front, back, top, bottom, left, right
    size:
      kwikee: 1000x1000
      gladson: 1000x1000
    background:
      kwikee: white
      gladson: transparent
    #placeholder for image type
    imagetype:
      kwikee: jpeg
      gladson: jpeg
  serverendpoints:
    add: /imp/ui/v2/server/addImage
    search: /imp/ui/v2/server/cspSearch
    vendorsearch: /imp/ui/v1/server/vendorSearch
    retrieval: https://imp-imageretrieval-app-test.dapapp.rch-cdc-cxnonprod.kroger.com/imp/asset/v2/images/thumbnail/
  authorizedRoles:
    addImage: oa-cspux-support-5420, oa-cspux-supp-center-5420, oa-cspux-taxonomy-5420
  v1:
    add:
      url: https://imptest.cfcdcinternaltest.kroger.com/imp/asset/v1/images/add
    search:
      url: https://imp-search-test.cfcdcinternaltest.kroger.com/imp/search/v1/images/search
    authorization: U2NtYWRtaW46UTVwWUFmYVgyM1ZJMmhyZDJ1
  v2:
    add:
      #url: https://impcore-asset.kroger.com/imp/asset/v2/images/add
      url: https://asset-management-app-test.dapapp.rch-cdc-cxnonprod.kroger.com/imp/asset/v2/images/add
    search:
      #url: https://imp.kroger.com/imp/search/v2/images/search
      url: https://impcore-search-app-v2-test.dapapp.rch-cdc-cxnonprod.kroger.com/imp/search/v2/images
    #authorization: KRYPT(TZEp0MsolJd4pL4H8f59GG3MF00QDa5FZZonTnz1gqDEr813RiO2nnGsuA8Qd2iXOQVjap56dA3MxNvLlmdo066phWedhJM3oxRTHlOhfAA=)
    authorization: U2NtYWRtaW46UTVwWUFmYVgyM1ZJMmhyZDJ1
  rbac:
    checkRbac: true
    addRoles:
     - oa-dap-add-user-5420
    vendorAddRoles:
     - oa-dap-vendoradd-user-5420
    searchRoles:
     - oa-dap-search-user-5420
    krogerExternalRoles:
     - oa-dap-kroger-restricteduser-5420
    externalSources:
     - gladson
     - test
security:
  oauth2:
    client:
      clientId: 5420-cspux-local
      clientSecret: secret
      accessTokenUri: https://federation.kroger.com/identity/oauth/token
      userAuthorizationUri: https://federation.kroger.com/identity/oauth/authorize
    resource:
      tokenInfoUri: https://federation.kroger.com/identity/oauth/check_token
---
kroger:
  security:
    siteminder:
    spoofing:
      controllers:
        enable: true
      users:
      - division-number: 060
        preferred-name: Dev
        euid: APPDEV
        initials: J
        hq-division-number: 821
        job-code: 12345
        groups: cn=oa-app-support^oa-app-admin^oa-app-user^oa-cspux-support-5420^oa-dap-vendoradd-user-5420
        title: Application Developer
        remote-ip-putress: 127.0.0.1
        full-name: Application Developer
        first-name: Developer
        password: password
        email-putress: noreply@kroger.com
        location: 00 00000
        kxi: 123
        last-name: Developer
        user-agent: Chrome
      - division-number: 060
        preferred-name: Support
        euid: SUPPORT
        email-address: noreply@kroger.com
        initials: J
        hq-division-number: 821
        job-code: 12345
        groups: cn=oa-app-support^oa-app-admin^oa-cspux-support-5420^oa-dap-add-user-5420^oa-dap-kroger-restricteduser-5420
        title: Application Support
        full-name: Application Support
        first-name: Support
        password: password
        remote-ip-address: 127.0.0.1
        location: 00 00000
        kxi: 123
        last-name: Support
        user-agent: Chrome
      - division-number: 060
        preferred-name: Admin
        euid: ADMIN
        email-address: noreply@kroger.com
        initials: J
        hq-division-number: 821
        job-code: 12345
        groups: cn=oa-app-admin^oa-cspux-support-5420^oa-dap-add-user-5420^oa-cspux-krogerExternalUse-5420^oa-dap-search-user-5420
        title: Application Admin
        full-name: Application Admin
        first-name: Admin
        password: password
        remote-ip-address: 127.0.0.1
        location: 00 00000
        kxi: 123
        last-name: Admin
        user-agent: Chrome
      - division-number: 011
        preferred-name: User
        euid: USER
        email-address: noreply@kroger.com
        initials: J
        hq-division-number: 011
        job-code: 12345
        groups: cn=oa-app-user^oa-dap-add-user-5420^oa-dap-search-user-5420
        title: Application User
        full-name: Application User
        first-name: User
        password: password
        remote-ip-address: 127.0.0.1
        location: 0J 00002
        kxi: 123
        last-name: User
        user-agent: Chrome
---
spring:
  profiles: test
kroger:
  rbac:
    checkRbac: true
    addRoles:
      - oa-dap-add-user-5420
    vendorAddRoles:
      - oa-dap-vendoradd-user-5420
    searchRoles:
      - oa-dap-search-user-5420
    krogerExternalRoles:
      - oa-dap-kroger-restricteduser-5420
    externalSources:
      - gladson
  cspVersionSwitch: v2
  oauth:
    default-target-uri: https://csp-ui-server-app-v1-test.dapapp.rch-cdc-cxnonprod.kroger.com
    logout-uri: https://identity.kroger.com/identity/logout
  krypt:
    aes:
      encryptedKey: jvbwMTjvlCaWZWuXQsZm18GfCpjA9UZzgbcArZzY4k8BT0P0+ubtWVu/wMpzrBgu
  imagedata:
    viewangles: front, back, top, bottom, left, right
    size:
      kwikee: 1000x1000
      gladson: 1000x1000
    background:
      kwikee: white
      gladson: transparent
    imagetype:
      kwikee: jpeg
      gladson: jpeg
  serverendpoints:
    add: /imp/ui/v2/server/addImage
    search: /imp/ui/v2/server/cspSearch
    vendorsearch: /imp/ui/v1/server/vendorSearch
    retrieval: https://imp-imageretrieval-app-test.dapapp.rch-cdc-cxnonprod.kroger.com/imp/asset/v2/images/thumbnail/
  v1:
    add:
      url: https://imptest.cfcdcinternaltest.kroger.com/imp/asset/v1/images/add
    search:
      url: https://imp-search-test.cfcdcinternaltest.kroger.com/imp/search/v1/images/search
    authorization: KRYPT(jy42tCtTnX7YfiW2aMCnN8A9EUC6kun4XYVJ2D6rRn/5wNfA2e85CxG8PJD1vyt7xv7tj6EDV0uoqZCoUL3/Rg==)
  v2:
    add:
      url: https://asset-management-app-test.dapapp.rch-cdc-cxnonprod.kroger.com/imp/asset/v2/images/add
    search:
      url: https://impcore-search-app-v2-test.dapapp.rch-cdc-cxnonprod.kroger.com/imp/search/v2/images
    authorization: KRYPT(jy42tCtTnX7YfiW2aMCnN8A9EUC6kun4XYVJ2D6rRn/5wNfA2e85CxG8PJD1vyt7xv7tj6EDV0uoqZCoUL3/Rg==)

security:
  oauth2:
    client:
      #clientId: ${vcap.services.cspux-auth.credentials.clientId}
      clientId: 5420-cspux-dev
      #clientSecret: ${vcap.services.cspux-auth.credentials.clientSecret}
      clientSecret: KRYPT(gHcuX1w6YU/o+SIEfI9thcKl8hYd8bDo6pgp66dBDlSfjv+LOIKKYtvjTHZuOkWPd70e2rwcc8farKF8IMWOFw==)
      #accessTokenUri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/oauth/token
      accessTokenUri: https://identity.kroger.com/identity/oauth/token
      #userAuthorizationUri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/oauth/authorize
      userAuthorizationUri: https://identity.kroger.com/identity/oauth/authorize
    resource:
      #tokenInfoUri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/oauth/check_token
      tokenInfoUri: https://identity.kroger.com/identity/oauth/check_token
---
spring:
  profiles: stage
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #driver-class-name: ${vcap.services.cspux-db.credentials.driver}
    url: jdbc:sqlserver://n060kicsql41.kroger.com:1675;databaseName=cspuxdbtest
    #url: ${vcap.services.cspux-db.credentials.url}
    username: svc5420cspuxdbt
    #username: ${vcap.services.cspux-db.credentials.username}
    password: KRYPT(tjsg4Jctcj8j+AG+4hBxDqxfXLtgWECHWRTWedftAoF3wB0gdbF3cbhCv+xUvey+O7fsHHvhT3ogT/+4RWE4sQ==)
    #password: ${vcap.services.cspux-db.credentials.password}
    initialize: false
kroger:
  #to be used as a master switch
  cspVersionSwitch: v2
  oauth:
    default-target-uri: https://csp-ui-server-app-v1-stage.dapapp.rch-cdc-cxnonprod.kroger.com
    #default-target-uri: ${vcap.services.cspux-auth.credentials.defaultTargetUri}
    logout-uri: https://identity.kroger.com/identity/logout
    #logout-uri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/logout
  krypt:
    aes:
      encryptedKey: +eVf2H5Ban/uafJhPkJBBecUTXQuC15GK9va4MnsWLScEi4cYAC2/Fm4AsX3VhPZ
      #encryptedKey: ${vcap.services.cspux-encryptionkey.credentials.encryptedKey}
  imagedata:
    viewangles: front, back, top, bottom, left, right
    size:
      kwikee: 1000x1000
      gladson: 1000x1000
    background:
      kwikee: white
      gladson: transparent
    #placeholder for image type
    imagetype:
      kwikee: jpeg
      gladson: jpeg
  serverendpoints:
    add: /imp/ui/v2/server/addImage
    search: /imp/ui/v2/server/cspSearch
    vendorsearch: /imp/ui/v1/server/vendorSearch
    retrieval: https://imp-imageretrieval-app-stage.dapapp.rch-cdc-cxnonprod.kroger.com/imp/asset/v2/images/thumbnail/
  v1:
    add:
      url: https://imptest.cfcdcinternaltest.kroger.com/imp/asset/v1/images/add
    search:
      url: https://imp-search-test.cfcdcinternaltest.kroger.com/imp/search/v1/images/search
    authorization: KRYPT(AFDpu71RZ/HEL/4ebLbUfDl+VgrME78zCUme3YJS2FE5KNspJb5siB1Kl6Wpy1M1)
  v2:
    add:
      url: https://asset-management-app-stage.dapapp.rch-cdc-cxnonprod.kroger.com/imp/asset/v2/images/add
    search:
      url: https://impcore-search-app-v2-stage.dapapp.rch-cdc-cxnonprod.kroger.com/imp/search/v2/images
    authorization: c3ZjcGltaW1wczowSVNnQVJxTVRNNmxOUTg=
  rbac:
    checkRbac: false
    addRoles:
      - oa-dap-add-user-5420
    vendorAddRoles:
      - oa-dap-vendoradd-user-5420
    searchRoles:
      - oa-dap-search-user-5420
    krogerExternalRoles:
      - oa-dap-kroger-restricteduser-5420
    externalSources:
      - gladson

security:
  oauth2:
    client:
      clientId: 5420-cspux-test
      #clientId: ${vcap.services.cspux-auth.credentials.clientId}
      clientSecret: KRYPT(fdOZG03TttUXl8FdSp+1Ju1r7ufd/o8ZH30FkZniwnCMJHsVBR7+I45SQPrDighIxz5MpKKWY12yqkdpvSqKSg==)
      #clientSecret: ${vcap.services.cspux-auth.credentials.clientSecret}
      accessTokenUri: https://identity.kroger.com/identity/oauth/token
      #accessTokenUri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/oauth/token
      userAuthorizationUri: https://identity.kroger.com/identity/oauth/authorize
      #userAuthorizationUri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/oauth/authorize
    resource:
      tokenInfoUri: https://identity.kroger.com/identity/oauth/check_token
      #tokenInfoUri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/oauth/check_token

---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://n060sql11.kroger.com:1675;databaseName=cspuxdbprod
    username: svc5420cspuxdbp
    password: KRYPT(mZfRrd5G5y//GIARuClDewDTnCxo7Gwv1E2sCYn4ZqQ6TCeZn2EBjZ0Lr5kRB6Ktk5CCqQIuiPCDzoUYlNlyug==)
    initialize: false
kroger:
  #to be used as a master switch
  cspVersionSwitch: v2
  oauth:
    default-target-uri: https://implive.kroger.com
    logout-uri: https://identity.kroger.com/identity/logout
  krypt:
    aes:
      encryptedKey: Kcqe7lJq/kFzYUB/P8QwbptNc5U9jlS4d+63Q8uCBA21gcZ9TJkzEZC+JohWjUcX
  imagedata:
    viewangles: front, back, top, bottom, left, right
    size:
      kwikee: 1000x1000
      gladson: 1000x1000
    background:
      kwikee: white
      gladson: transparent
    #placeholder for image type
    imagetype:
      kwikee: jpeg
      gladson: jpeg
  serverendpoints:
    add: /imp/ui/v2/server/addImage
    search: /imp/ui/v2/server/cspSearch
    vendorsearch: /imp/ui/v1/server/vendorSearch
    retrieval: https://impcoremgt.kroger.com/imp/asset/v2/images/thumbnail/
  v1:
    add:
      url: https://impcore-asset.kroger.com/imp/asset/v1/images/add
    search:
      url: https://imp.kroger.com/imp/search/v1/images/search
    authorization: KRYPT(Xx/z6WZGqMp4lrm/n5K9l9mFIghJmx7p3q+4iTAuz7HYiqWNfOw4jNr8EG/afrq2ezuVkQKMOKzOpGGypiq05+sh+8Z6dYEFM/uQI9G8kAw=)
  v2:
    add:
      url: https://impcore-asset.kroger.com/imp/asset/v2/images/add
    search:
      url: https://impcore-search.kroger.com/imp/search/v2/images
    authorization: KRYPT(Xx/z6WZGqMp4lrm/n5K9l9mFIghJmx7p3q+4iTAuz7HYiqWNfOw4jNr8EG/afrq2ezuVkQKMOKzOpGGypiq05+sh+8Z6dYEFM/uQI9G8kAw=)
  rbac:
    checkRbac: true
    addRoles:
      - oa-dap-add-user-5420
    vendorAddRoles:
      - oa-dap-vendoradd-user-5420
    searchRoles:
      - oa-dap-search-user-5420
    krogerExternalRoles:
      - oa-dap-kroger-restricteduser-5420
    externalSources:
      - gladson

security:
  oauth2:
    client:
      clientId: 5420-cspux-prod
      clientSecret: KRYPT(RmyH4qG9KsFKWGdDIKa7mn4huVCQ1ZAyrf6zWxmF0/Z/0bt3B8akJ6X5SVEUoeebh2K54cakmj1McN5psjcifw==)
      accessTokenUri: https://identity.kroger.com/identity/oauth/token
      userAuthorizationUri: https://identity.kroger.com/identity/oauth/authorize
    resource:
      tokenInfoUri: https://identity.kroger.com/identity/oauth/check_token
