---
spring:
  application:
    name: Content Services Platform UI App
  output:
    ansi:
      enabled: detect
  profiles:
    active: local,SPOOFING
  mvc:
    view:
      suffix: .html
#server:
  #context-path: /
  #port: 8080
kroger:
  ldap:
    filter-order: -10
  management:
    security:
      roles: oa-cspux-support-5420
      enabled: false
  eaf:
    version: 5.0.2
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,krypt,keepalive
#logging:
  #level:
    #org.springframework.security: DEBUG
---
spring:
  profiles: local
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=testdb
    username: ''
    password: ''
    initialize: false
kroger:
  oauth:
    default-target-uri: http://localhost:8080
    logout-uri: https://federation.kroger.com/identity/logout
  krypt:
    aes:
      encryptedKey: uY266kD0KlmVxQxa1gLAvSCFdAFtS4OBh/kT4oQsAEO1ujL/BlkhpqXohd8HDDW8

security:
  oauth2:
    client:
      clientId: 5420-cspux-local
      clientSecret: secret
      accessTokenUri: https://federation.kroger.com/identity/oauth/token
      userAuthorizationUri: https://federation.kroger.com/identity/oauth/authorize
    resource:
      tokenInfoUri: https://federation.kroger.com/identity/oauth/check_token
---
spring:
  profiles: cloud
  datasource:
    driver-class-name: ${vcap.services.cspux-db.credentials.driver}
    url: ${vcap.services.cspux-db.credentials.url}
    username: ${vcap.services.cspux-db.credentials.username}
    password: ${vcap.services.cspux-db.credentials.password}
    initialize: false
kroger:
  oauth:
    default-target-uri: ${vcap.services.cspux-auth.credentials.defaultTargetUri}
    logout-uri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/logout
  krypt:
    aes:
      encryptedKey: ${vcap.services.cspux-encryptionkey.credentials.encryptedKey}

security:
  oauth2:
    client:
      clientId: ${vcap.services.cspux-auth.credentials.clientId}
      clientSecret: ${vcap.services.cspux-auth.credentials.clientSecret}
      accessTokenUri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/oauth/token
      userAuthorizationUri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/oauth/authorize
    resource:
      tokenInfoUri: ${vcap.services.cspux-auth.credentials.identityServerUri}/identity/oauth/check_token
---
spring:
  profiles: unittest
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=testdb
    username: ''
    password: ''
    initialize: false
kroger:
  oauth:
    default-target-uri: http://localhost:8080
    logout-uri: https://federation.kroger.com/identity/logout
  krypt:
    aes:
      encryptedKey: XGjOczcpxu8+8V0QcFNgmoIwGBWd7miVDNy0GnXVMayJIPZhxfNfszKdNRCRPVx8
security:
  oauth2:
    client:
      clientId: 5420-cspux-local
      clientSecret: secret
      accessTokenUri: https://federation.kroger.com/identity/oauth/token
      userAuthorizationUri: https://federation.kroger.com/identity/oauth/authorize
    resource:
      tokenInfoUri: https://federation.kroger.com/identity/oauth/check_token
