apiVersion: apps/v1
kind: Deployment
metadata:
  name: csp-ui-server-app-v1-stage
  namespace: dapapp-stage
spec:
  selector:
    matchLabels:
      app: csp-ui-server-app-v1-stage
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: csp-ui-server-app-v1-stage
    spec:
      imagePullSecrets:
        - name: csp-ui-app-stage-secrets
      containers:
        - name: csp-ui-server-app-v1-stage
          image: docker-prod.artifactory-edge.kroger.com/imp/dap/csp-ui-app/v1/csp-ui-server-app:${{ env.RELEASE_TAG }}
          imagePullPolicy: Always   #This forces kubernetes to pull a docker image everytime even with the same tag ids
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1024Mi"
            limits:
              memory: "2048Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                secretKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: csp-ui-server-app-v1-settings
---
apiVersion: v1
kind: Service
metadata:
  name: csp-ui-server-app-v1-stage
  namespace: dapapp-stage
  labels:
    app: csp-ui-server-app-v1-stage
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
  selector:
    app: csp-ui-server-app-v1-stage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: csp-ui-server-app-stage
  namespace: dapapp-stage
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: krogerissuer
    cert-manager.io/issuer-kind: KrogerIssuer
    cert-manager.io/issuer-group: certs
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-body-size: 999m
spec:
  tls:
    - hosts:
        #hostname of your application *.dapapp.rch-cdc-cxnonprod.kroger.com
        - csp-ui-server-app-v1-stage.dapapp.rch-cdc-cxnonprod.kroger.com
      secretName: csp-ui-server-app-stage-cert
  rules:
    - host: csp-ui-server-app-v1-stage.dapapp.rch-cdc-cxnonprod.kroger.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: csp-ui-server-app-stage
                port:
                  number: 80
