name: Build_Docker_Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_TAG: v1.0
  DOCKER_BASE_REPOSITORY: docker-prod.registry.kroger.com

jobs:

  build:

    runs-on: [self-hosted, Linux, X64, tsa, kroger]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Repo Login
        run: docker login ${{env.DOCKER_BASE_REPOSITORY}} --username ${{ secrets.ARTIFACTORY_USERNAME }} --password ${{ secrets.ARTIFACTORY_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ${{env.DOCKER_BASE_REPOSITORY}}/imp/dap/csp-ui-app/v1/csp-ui-server-app:${{ env.IMAGE_TAG }} .
      - name: Push Docker Image
        run: docker push ${{env.DOCKER_BASE_REPOSITORY}}/imp/dap/csp-ui-app/v1/csp-ui-server-app:${{ env.IMAGE_TAG }}
